services:
  database:
    image: 'postgres:15.2'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=ecommerce'
      - 'POSTGRES_PASSWORD=QUVAstop**11'
    volumes:
      - './volumes/ecommerce-app/postgres:/var/lib/postgresql/data'
